### ISSUE TITLE
How to call ViewController in a Storyboard?

### ISSUE THREAD

**Issue by entaku0818** [tarunon/Instantiate#35]
I use Instantiate in my project.
Thank you as always.

I want to write source code as below

```swift
let storyboard = UIStoryboard(name: "StoryboardName", bundle: nil)
firstViewController = storyboard.instantiateViewController(withIdentifier: FirstViewController.nameOfClass)
```

I think can in Instantiate.
However, I don't know how to use in Instantiate.

Could you tell me how to use?

**Comment by tarunon** [comment]
https://github.com/tarunon/Instantiate/blob/master/Sources/Instantiate/Storyboard.swift#L45
@entaku19890818 Can't you use it? We can solve it this solution if my understanding is correct 😉

**Comment by entaku0818** [comment]
This solution is probably correct.

But I don't know how to define viewcontroller and how to call viewcontroller.

**Comment by entaku0818** [comment]
Could you tell me how to setting "instantiate source"?

**Comment by tarunon** [comment]
```swift
class FirstViewController: UIViewController, StoryboardInstantiatable {
    static let storyboardName = "StoryboardName"
    static let instantiateSource = InstantiateSource.identifier("FirstViewController")
}
```
Maybe that's fine, I think...

**Comment by entaku0818** [comment]
I did it!
Thank you very much:) You've been very helpful.
