### ISSUE TITLE
Could not fetch v4.0.0 from Cocoapods

### ISSUE THREAD

**Issue by imaizume** [tarunon/Instantiate#38]
Hi @tarunon 👋 
I want to use `v4.0.0` but could not download with specifying version as `pod 'Instantiate', '~> 4.0'` and then `pod update`.

Result:

```shell
[!] CocoaPods could not find compatible versions for pod "Instantiate":
  In Podfile:
    Instantiate (~> 4.0)

None of your spec sources contain a spec satisfying the dependency: `Instantiate (~> 4.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I think you forgot to release in [Cocoapods](https://cocoapods.org/pods/Instantiate) because it said `v3.0.0` was the latest.

**Comment by tarunon** [comment]
Thanks notice that, yes, I forgot update Cocoapods. I just push latest version, please check it 🙏
