### ISSUE TITLE
Question about Test cases

### ISSUE THREAD

**Issue by ericji-o** [tarunon/Instantiate#39]
Just one question. 
If need to test UI. I need to set public/internal for the class members which are UI Control.
Because I need to compare dependency value(mock data) with the value in UI.

I used to set private/fileprivate to prevent UI member from changing by outside. 
How to use dependency but still keep members safe.

Thanks

**Comment by tarunon** [comment]
I'm sorry, but for now, it's difficult for me that understanding gist of your question. Is it relevant to this library? 
If you can explain detail with code, It's possible to help me.

**Comment by ericji-o** [comment]
Sorry I havent explained it clearly.

Library is OK. Also it helped me understand DI more clearly. Thanks
Because I prefer to write UI by using codes. I think in one class it is unnecessary to set all class members be public/internal. Especially in the teamwork. it will make source codes safe.

For example
✅
Class OneViewController {
       private let someView = UIView()
}
❌
Class OneViewController {
      let someView = UIView()
}

I read the test case like this.
XCTAssertEqual(tableCells[0].label.text, "1")

If using code. cell should set ''label'' property -> public/internal. 
How do you think about access modifiers or protection level?
I hope you can get my point. lol

**Comment by tarunon** [comment]
Seems this question isn't related this library.  😕
But I guess you can try XCUITest instead of XCTest, XCUITest provide API that access to private UI components.
