### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by jormungand2006** [tarunon/Instantiate#41]
When I try to add package of Instantiate via SPM, I get the following error: 

> because Instantiate >=2.1.0 contains incompatible tools version and root depends on Instantiate 4.0.0..<5.0.0, version solving failed.

environment: Xcode 12.2

So is there a workaround?
Thank you.

<img width="702" alt="スクリーンショット 2020-12-16 10 23 20" src="https://user-images.githubusercontent.com/6168526/102292680-04e33280-3f89-11eb-8b1a-d4bdd9f59e53.png">

**Comment by tarunon** [comment]
I found package resolve error on Package.swift, and fixed them in new release 4.0.1. Could you please try it again? 🙏

**Comment by jormungand2006** [comment]
It works fine with 4.0.1!
Thank you for your cooperation.
